### ISSUE TITLE
Logo mask covers the ‘me’ inside the veggie

### ISSUE THREAD

**Issue by JTurecki** [shuzootani/eating-for-me#32]

**Comment by shuzootani** [comment]
<img width="127" alt="screen shot 2018-12-10 at 18 05 49" src="https://user-images.githubusercontent.com/19385183/49773502-4360fb00-fca6-11e8-92a2-5e254723a5f5.png">

<img width="134" alt="screen shot 2018-12-10 at 18 05 54" src="https://user-images.githubusercontent.com/19385183/49773509-4825af00-fca6-11e8-9130-9652c757e40d.png">
